use_frameworks!

platform :ios, '15.0'

target 'BadgeLog_Example' do
  pod 'BadgeLog', :path => '../'

  target 'BadgeLog_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase' 
    pod 'Nimble-Snapshots' 
  end
end
